networks:
  lendmate-net:
    external: true

services:
  user-service:
    image: "user-service"
    build: .
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_service_db
      SPRING_DATASOURCE_USERNAME: lendmate
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: >-
        -XX:MaxRAMPercentage=60.0 
        -XX:+UseSerialGC 
        -Xss256k 
        -XX:MaxMetaspaceSize=100m
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: product-service
    mem_limit: 300m
    restart: unless-stopped
    networks:
      - lendmate-net

volumes:
  postgres_data: