springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  forward-headers-strategy: framework
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate

gateway:
  security:
    enabled: false
