spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db_dev
    username: lendmate
    password: lendmate
  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false

logging:
  level:
    com:
      project:
        user-service: DEBUG

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
  resource:
    attributes:
      service.name: ${spring.application.name}
  logs:
    exporter: none
  traces:
    exporter: otlp
  metrics:
    exporter: none
  java:
    disabled:
      resource:
        providers: io.opentelemetry.instrumentation.resources.ProcessResourceProvider