spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db_dev
    username: lendmate
    password: lendmate
  jpa:
    show-sql: true

logging:
  level:
    com:
      project:
        user-service: DEBUG

