springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  forward-headers-strategy: framework

spring:
  application:
    name: user-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: lendmate-kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

gateway:
  security:
    enabled: true